# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

WORKDIR /app

# Install dependencies and build project
COPY package.json package-lock.json tsconfig.json ./
COPY src ./src

RUN npm install --ignore-scripts \
    && npm run build

# Default command to run the MCP server
ENTRYPOINT ["node", "build/index.js"]
